Guia de Contribuição
fga-eps-mds/EPS-2020-2-G2 pull request #16
Opened 2021-02-12 00:52 UTC by devsalula

Foi desenvolvido um guia de contribuição para novos desenvolvedores.

### issues linkadas
#2

2021-02-12 18:36 UTC, Phe0 commented
@devsalula coloca o guia de contribuição lá na wiki também por favor, junto do código de conduta

2021-02-12 18:51 UTC, Phe0 requested changes

2021-02-12 18:51 UTC, Phe0 commented on CONTRIBUTING.md
> +Adoramos a contribuição de novas pessoas! Gostaríamos de transformar a contribuição desse projeto o mais fácil possível. E adoramos todos os tipos de contribuição, seja:
```suggestion
Adoramos a contribuição de novas pessoas! Gostaríamos de transformar a contribuição desse projeto na mais fácil possível. E adoramos todos os tipos de contribuição, seja:
```

2021-02-13 01:34 UTC, devsalula commented
@Phe0 correções feitas

2021-02-13 11:10 UTC, Phe0 approved these changes

2021-02-13 11:10 UTC, merged