Update MKDocs version and change Docker image
fga-eps-mds/EPS-2020-2-G2 pull request #30
Opened 2021-02-16 17:46 UTC by Victor-Buendia

Co-authored-by: Brian Pina de Sá <brian.pina2001@gmail.com>

2021-02-18 18:56 UTC, devsalula requested changes
Uma questão, quando rodei aqui, as tabelas elas ficaram todas menores. Imagino que lá no css que vcs deixaram comentado, ele só estava esticando a tabela. 
Vocês não consegue tentar esticar o conteúdo das tabelas? Se não, pelo menos conseguem centralizar as tabelas no documento.

2021-02-18 18:56 UTC, devsalula commented on docs/assets/css/extra.css
> +/* .md-typeset__table {    <- Largura da tabela
Se não tá sendo utilizado, pode apagar.

2021-02-18 19:15 UTC, Victor-Buendia commented on docs/assets/css/extra.css
> +/* .md-typeset__table {    <- Largura da tabela
@devsalula A gente pesquisou vários fixes para essa questão, porque também reparamos que estava menor o tamanho das tabelas, mas vimos que alguns outros elementos - como o menu - tiveram o design alterado só pela versão do MKDocs. Assim, presumimos que foi uma alteração do MKDocs de fazer as tabelas serem menores.

Contudo, vamos reavaliar essa questão para resubmeter o PR - removendo também a parte comentada.

2021-02-19 13:20 UTC, devsalula commented on docs/assets/css/extra.css
> +/* .md-typeset__table {    <- Largura da tabela
Beleza, aguardo o retorno

2021-02-19 22:18 UTC, Victor-Buendia commented
@devsalula Já fizemos a atualização, Brian e eu com a ajuda do Féo. A versão final é a submetida.

2021-02-20 00:26 UTC, devsalula commented
Parabéns pelo trabalho galera, as tabelas centralizadas ficaram bem melhor! 
Porém, encontrei outro problema. Ao entrar na tela de Sprint Planning, a tabela de pareamento não permite dar scroll para a esquerda e visualizar as pessoas que estão na primeira coluna.
![mds-eps-bug](https://user-images.githubusercontent.com/35435199/108575472-1a623900-72f9-11eb-8fed-df92dea0ead5.png)

2021-02-20 00:27 UTC, devsalula requested changes
Parabéns pelo trabalho galera, as tabelas centralizadas ficaram bem melhor! 
Porém, encontrei outro problema. Ao entrar na tela de Sprint Planning, a tabela de pareamento não permite dar scroll para a esquerda e visualizar as pessoas que estão na primeira coluna.
![mds-eps-bug](https://user-images.githubusercontent.com/35435199/108575472-1a623900-72f9-11eb-8fed-df92dea0ead5.png)

2021-02-20 11:14 UTC, Victor-Buendia commented
Removi a tabela como conversamos na Sprint Planning. O Blanco vai alterá-la.

2021-02-20 14:50 UTC, devsalula approved these changes
Grande trabalho @Victor-Buendia @DLBrianPina @Phe0

2021-02-20 14:50 UTC, merged